export {
  addProject,
  checkProjectUniqueness,
  createWorkspace,
  getProjectCatalogTree,
  getProjectProfileSnapshot,
  getWorkspaceTree,
  listProjects,
  listRecentProjects,
  listWorkspaces,
  pickProjectDirectory,
  removeProject,
  removeRecentProject,
  removeWorkspace,
  reorderWorkspaces,
  touchProjectOpened,
  updateProject,
  updateWorkspace,
  type ProjectProfileFile,
  type ProjectProfileSnapshot,
} from "@/api/project";
