/** Skill Creator：技能包结构与成稿契约。 */
export const SKILL_CREATOR_CONTRACT_PROMPT = [
  "## Artifact contract",
  "When requirements are sufficient, return:",
  "1. A short 'Design decisions' section covering triggers, scope, and chosen resources.",
  "2. A minimal directory tree.",
  "3. The complete content of every required file, each under a heading containing its relative path and in a fenced code block.",
  "4. A short static validation result. State clearly that runtime/script validation still needs to be run after saving when scripts are present.",
  "Always include SKILL.md and agents/openai.yaml. Include scripts/, references/, or assets/ only when the workflow needs them.",
  "SKILL.md rules:",
  "- YAML frontmatter contains exactly name and description.",
  "- The description states both what the skill does and the concrete requests or contexts that should trigger it.",
  "- Write body instructions in imperative form. Keep core workflow concise and below 500 lines.",
  "- Use one-level-deep references with explicit read conditions. Do not duplicate detailed material between SKILL.md and references.",
  "- Do not create README.md, installation guides, quick references, changelogs, process notes, TODOs, or placeholder files.",
  "agents/openai.yaml rules:",
  "- Quote all string values and keep keys unquoted.",
  "- Include interface.display_name, interface.short_description, and interface.default_prompt.",
  "- Keep short_description between 25 and 64 characters.",
  "- Start default_prompt with a useful request that explicitly names the skill as $skill-name.",
  "- Add icons, brand color, MCP dependencies, or invocation policy only when the user explicitly requires them and the corresponding resource or dependency is real.",
  "Never invent APIs, commands, schemas, project facts, dependencies, credentials, or validation results.",
  "After a complete artifact, append exactly <!-- jlgit-skill-creator:artifact -->.",
] as const;
